---
- name: PRE
  ansible.builtin.include_tasks: pre/main.yml

- name: WAN | DDNS
  ansible.builtin.include_tasks: wan/ddns.yml

- name: LAN
  ansible.builtin.include_tasks: lan/main.yml

- name: FIREWALL | GENERAL
  ansible.builtin.include_tasks: firewall/general.yml
