---
- name: nvram commit
  nvram:
    command: commit

- name: restart ddns
  ansible.builtin.raw: service restart_ddns

- name: restart dnsmasq
  ansible.builtin.raw: service restart_dnsmasq

- name: restart firewall
  ansible.builtin.raw: service restart_firewall

- name: restart httpd
  ansible.builtin.raw: service restart_httpd

- name: restart letsencrypt
  ansible.builtin.raw: service restart_letsencrypt

- name: restart wireless
  ansible.builtin.raw: service restart_wireless

- name: reboot
  ansible.builtin.raw: reboot

# restart_cstats
# restart_dualwan
# restart_fanctrl
# restart_fbwifi
# restart_fbwifi_register
# restart_iptrestore
# restart_mdns
# restart_nas_services
# restart_rstats
# restart_upnp
# restart_wan_line
